config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :projects do
    member { get 'details' }
  end
  resources :links
  resources :guides
  resources :photos
  resources :posts
  resources :messages

  get '/about' => 'home#about'
  get '/tree' => 'home#tree'
  get '/calendar' => 'home#calendar'
  get '/wall' => 'posts#index'
  get '/chat' => 'chat#index'
  get '/chat/:channel' => 'chat#channel'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login' => redirect('/auth/github')
  delete '/logout' => 'sessions#destroy'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  store :github_data, accessors: [:gravatar, :description, :last_commit_date, :last_commit_message]
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource param_method: :project_params
  skip_authorize_resource :only => :details

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /project/1/details.json
  def details
    project = Project.find(params[:id])
    details = GithubData.new(project.username, project.repo)
    details.fetch!

    render json: details
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private

  def project_params
    params.require(:project).permit(:username, :repo, :website)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def github_user(user)
    link_to user, "https://github.com/#{user}"
  end

  def github_repo(user, repo)
    link_to repo, "https://github.com/#{user}/#{repo}"
  end
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username, 'Login na Githubie'
    = f.text_field :username
  .field
    = f.label :repo, 'Nazwa repozytorium na Githubie'
    = f.text_field :repo
  .field
    = f.label :website, 'Adres strony internetowej'
    = f.text_field :website
  .actions
    = f.submit 'Zapisz', :class => 'btn btn-success'

app/views/projects/edit.html.haml
%h1 Edycja

= render 'form'

= link_to 'Wróc do listy', projects_path

app/views/projects/index.html.haml
- provide(:title, 'Projekty')
%h1 Nasze projekty

= link_to '+ Nowy projekt', new_project_path, :class => 'btn btn-primary'

.projects
  - @projects.each do |project|
    .project-box{'data-project' => project.id}
      .project-info
        .pull-left.half
          = image_tag ((project.gravatar.present?) ? project.gravatar : 'logos/octocat.png')
        .pull-left.half
          %strong Login:
          %span= github_user(project.username)
          %strong Repozytorium:
          %span= github_repo(project.username, project.repo)
          - if project.website.present?
            %strong Strona:
            %span= link_to project.website, project.website
      .project-details
        .description
          %strong Opis projektu:
          %span= project.description
        .last-commit-message
          %strong Ostatni commit:
          %span= project.last_commit_message
        .last-commit-date
          %strong Data ostatniego commitu:
          %span= project.last_commit_date
      .project-actions
        .btn-group
          - if can?(:edit, project)
            = link_to "Edytuj", edit_project_path(project), :class => "btn btn-success"
          - if can?(:edit, project)
            = link_to "Usuń", project_path(project), :confirm => 'Na pewno?', :method => :delete, :class => "btn btn-danger"

app/views/projects/new.html.haml
- provide(:title, 'Dodaj projekt')
%h1 Nowy projekt

= render 'form'

= link_to 'Wróc do listy', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b User:
  = @project.user
%p
  %b Repo:
  = @project.repo

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path