config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :projects do
    member { get 'details' }
  end
  resources :links
  resources :guides
  resources :photos
  resources :posts
  resources :messages

  get '/about' => 'home#about'
  get '/tree' => 'home#tree'
  get '/calendar' => 'home#calendar'
  get '/wall' => 'posts#index'
  get '/chat' => 'chat#index'
  get '/chat/:channel' => 'chat#channel'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login' => redirect('/auth/github')
  delete '/logout' => 'sessions#destroy'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:description, :picture)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= form_for(@photo, :html => { :multipart => true }) do |f|
  - if @photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :picture
    = f.file_field :picture
    = f.hidden_field :picture_cache
  .actions
    = f.submit 'Save'

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', photos_path

app/views/photos/index.html.haml
%h1 Listing photos

%table
  %tr
    %th Description
    %th Picture
    %th
    %th
    %th

  - @photos.each do |photo|
    %tr
      %td= photo.description
      %td= photo.picture
      %td= link_to 'Show', photo
      %td= link_to 'Edit', edit_photo_path(photo)
      %td= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Photo', new_photo_path

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', photos_path

app/views/photos/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @photo.description
%p
  %b Picture:
  = image_tag(@photo.picture_url, :width => 600) if @photo.picture.present?

= link_to 'Edit', edit_photo_path(@photo)
\|
= link_to 'Back', photos_path