config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :projects do
    member { get 'details' }
  end
  resources :links
  resources :guides
  resources :photos
  resources :posts
  resources :messages

  get '/about' => 'home#about'
  get '/tree' => 'home#tree'
  get '/calendar' => 'home#calendar'
  get '/wall' => 'posts#index'
  get '/chat' => 'chat#index'
  get '/chat/:channel' => 'chat#channel'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login' => redirect('/auth/github')
  delete '/logout' => 'sessions#destroy'

end

app/models/guide.rb
class Guide < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders, :history]

  validates :title, :content, :presence => true

  belongs_to :user

end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  load_and_authorize_resource

  # GET /guides
  # GET /guides.json
  def index
    @guides = Guide.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guides }
    end
  end

  # GET /guides/1
  # GET /guides/1.json
  def show
    @guide = Guide.find(params[:id])
    if request.path != guide_path(@guide)
      redirect_to @guide, status: :moved_permanently
    end
  end

  # GET /guides/new
  # GET /guides/new.json
  def new
    @guide = Guide.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guide }
    end
  end

  # GET /guides/1/edit
  def edit
    @guide = Guide.find(params[:id])
  end

  # POST /guides
  # POST /guides.json
  def create
    @guide = Guide.new(guide_params)
    @guide.user_id = current_user.id

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guide was successfully created.' }
        format.json { render json: @guide, status: :created, location: @guide }
      else
        format.html { render action: "new" }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guides/1
  # PUT /guides/1.json
  def update
    @guide = Guide.find(params[:id])

    respond_to do |format|
      if @guide.update_attributes(guide_params)
        format.html { redirect_to @guide, notice: 'Guide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/1
  # DELETE /guides/1.json
  def destroy
    @guide = Guide.find(params[:id])
    @guide.destroy

    respond_to do |format|
      format.html { redirect_to guides_url }
      format.json { head :no_content }
    end
  end

  private

  def guide_params
    params.require(:guide).permit(:title, :content)
  end
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_form.html.haml
= form_for @guide do |f|
  -if @guide.errors.any?
    #error_explanation
      %h2 Operacja nie powiodła się:
      %ul
        - @guide.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Zapisz', :class => 'btn btn-success'

app/views/guides/edit.html.haml
- provide(:title, 'Edytuj przewodnik')
%h1 Edycja

= render 'form'

= link_to 'Pokaż', @guide
\|
= link_to 'Wróć do listy', guides_path

app/views/guides/index.html.haml
- provide(:title, 'Przewodniki')
%h1 Przewodniki

= link_to '+ Nowy przewodnik', new_guide_path, :class => 'btn btn-primary'

.guides
  - @guides.each do |guide|
    .guide
      %h3= link_to guide.title, guide
      = link_to('Edytuj', edit_guide_path(guide)) if can?(:edit, guide)
      = link_to('Usuń', guide, :confirm => 'Na pewno?', :method => :delete) if can?(:destroy, guide)

app/views/guides/new.html.haml
- provide(:title, 'Dodaj przewodnik')
%h1 Nowy przewodnik

= render 'form'

= link_to 'Wróć do listy', guides_path

app/views/guides/show.html.haml
- provide(:title, 'Przewodniki')
%p#notice= notice

%h1= @guide.title

= markdown @guide.content

- if can?(:edit, @guide)
  = link_to('Edytuj', edit_guide_path(@guide)) 
  \|
= link_to 'Wróć do listy', guides_path