config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :projects do
    member { get 'details' }
  end
  resources :links
  resources :guides
  resources :photos
  resources :posts
  resources :messages

  get '/about' => 'home#about'
  get '/tree' => 'home#tree'
  get '/calendar' => 'home#calendar'
  get '/wall' => 'posts#index'
  get '/chat' => 'chat#index'
  get '/chat/:channel' => 'chat#channel'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login' => redirect('/auth/github')
  delete '/logout' => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<div class="footer">
	<span class="kontakt"><a href="mailto:&#119;&#101;&#099;&#097;&#110;&#100;&#111;&#105;&#116;&#064;&#111;&#110;&#114;&#097;&#105;&#108;&#115;&#046;&#112;&#108;">&#119;&#101;&#099;&#097;&#110;&#100;&#111;&#105;&#116;&#064;&#111;&#110;&#114;&#097;&#105;&#108;&#115;&#046;&#112;&#108;</a>
	</span> 
    <small>
      Ruby Wednesday 2012
    </small>
</div>

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %span{:class => (:active if current_page?(root_path))}
        = link_to 'Ruby on Rails #{w_środy}', root_path, id: "logo"
      .nav-collapse
        %ul.nav.pull-right
          %li{:class => (:active  if current_page?(about_path))}
            = link_to 'O nas', about_path
          %li{:class => (:active if nav_helper('projects'))}
            = link_to 'Projekty', projects_path
          %li{:class => (:active if nav_helper('links'))}
            = link_to 'Linki', links_path
          %li.dropdown{:class => ["visible-desktop", (:active if nav_helper('guides') || current_page?(tree_path))]}
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#menu1"}
              Materiały
              %b.caret
            %ul.dropdown-menu
              %li= link_to 'Drzewo katalogów', tree_path
              %li.divider
              %li= link_to 'Przewodniki', guides_path
          %li{:class => ["hidden-desktop", (:active if current_page?(tree_path))]}
            = link_to 'Drzewo katalogów', tree_path
          %li{:class => ["hidden-desktop", (:active if nav_helper('guides'))]}
            = link_to 'Przewodniki', guides_path
          - if current_user.present?
            %li{:class => (:active if nav_helper('posts'))}
              = link_to 'Wall', wall_path
          %li.divider-vertical
          = render 'layouts/navbar'

app/views/layouts/_navbar.html.haml
- if current_user.present?
  %li.avatar.visible-desktop
    = image_tag current_user.avatar_url
  %li.dropdown{:class => ['active', 'visible-desktop']}
    %a.dropdown-toggle.home{ :href => '#', 'data-toggle' => "dropdown"}
      = current_user.username
      %b.caret
    %ul.dropdown-menu
      %li= link_to 'Logout', logout_path, method: :delete
  %li.hidden-desktop
    %a.btn-danger{:href => logout_path}
      %i.icon-user.icon-white
      = 'Wyloguj ' + current_user.username
- else
  %li{ :class => if nav_helper('sessions') then 'active' end }= link_to 'Login', login_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv='content-type' content='text/html; charset=utf-8' />
  <meta name='viewport' content='width=device-width, initial-scale=1.0' />
  <title>We can do it! &raquo; <%= yield(:title) %></title>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro&amp;subset=latin-ext,latin' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag '/favicon.ico' %>
  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
  <div id="wrap">
    <div id="main" class="container clear-top">
     	 <%= yield %>
    </div><!-- main -->
  </div><!-- wrap -->
  <%= render 'layouts/footer' %>
</body>
</html>